function defaults = solar_sail_hybrid_pid_defaults(Euler0, AngularRate0)
%SOLAR_SAIL_HYBRID_PID_DEFAULTS Return default parameters, controller, and scenario structs.
%   Provides baseline configuration for attitude control simulation.
%   Optional: Euler0 (3x1 rad) and AngularRate0 (3x1 rad/s) override initial conditions.

defaults = struct();

% --- Initial Conditions ---------------------------------------------------
defaults.parameters.initial = struct( ...
    'absoluteEuler321', Euler0, ...
    'angularRate',   AngularRate0, ...
    'integralState', [0; 0; 0], ...
    'vaneDeflection', [0; 0; 0; 0], ...
    'rcdReflectivity', [0; 0; 0; 0]);

% --- Spacecraft Geometry --------------------------------------------------
defaults.parameters.geometry = struct( ...
    'sailSide', 40, ...
    'sailArea', 1600, ...
    'mass', 160, ...
    'inertia', diag([6000 3000 3000]), ...
    'vaneCount', 4, ...
    'vaneDofPerVane', 1, ...
    'vaneArea', 25, ...
    'vaneExtension', 5);   
                           
% --- Solar Environment ---------------------------------------------------
defaults.parameters.environment = struct( ...
    'Psrp', 4.604e-6, ...                    % N/m^2 at 0.993 AU  (Sec. 2.1)
    'eta', 1.8, ...                          % efficiency factor (absorption + specular reflection)
    'alphaCmd', atan(1 / sqrt(2)));

% --- Vane Actuator Parameters (Reflectivity Control) -------------------
defaults.parameters.vanes = struct( ...
    'deflectionLimit', deg2rad(35), ...      % delta_rc,max  (roll vanes)
    'pitchDeflectionLimit', deg2rad(35), ... % delta_pc,max  (pitch vanes)
    'rateLimit', deg2rad(5), ...
    'timeConstant', 10, ...
    'thetaLimit', deg2rad(40), ...
    'muTx', 5e-4);

% --- RCD Actuator Parameters (Reflectivity Modulation) ----------------
defaults.parameters.rcd = struct( ...
    'quadrantArea', 400, ...                 % A_sail/4           (Sec. 2.5.1)
    'centroidOffset', 10, ...
    'reflectivityLimit', 0.30, ...
    'timeConstant', 20);

% --- Disturbance Model ------------------
defaults.parameters.disturbance = struct( ...
    'enable', true, ...
    'cmCpOffset', 0.10);


% --- PID Controller Parameters -------------------------------------------
defaults.controller = struct( ...
    'wn', [1.0e-3 1.0e-3 1.0e-3], ...
    'zeta', [0.80 0.80 0.80], ...
    'wi', [2.5e-4 2.5e-4 2.5e-4], ...
    'Tintmx', 2.5e-3, ...
    'gamma0', 0.50, ...
    'atrans', deg2rad(15), ...                % transition angle for gamma modulation
    'esing', 1e-6);                           % small epsilon to prevent singularities

% --- Simulation Scenario Parameters --------------------------------------
defaults.scenario = struct( ...
    'tEnd', 20 * 3600, ...
    'dt', 4.0, ...
    'summaryWindowFraction', 0.10, ...
    'savePlots', false, ...
    'plotFolder', 'plots');
end