function defaults = solar_sail_hybrid_pid_defaults()
defaults = struct();

defaults.parameters.initial = struct( ...
    'attitudeError321', deg2rad([5; -4; 10]), ...
    'angularRate', [0; 0; 0], ...
    'integralState', [0; 0; 0], ...
    'vaneDeflection', [0; 0; 0; 0], ...
    'rcdReflectivity', [0; 0; 0; 0]);

defaults.parameters.geometry = struct( ...
    'sailSide', 40, ...
    'sailArea', 1600, ...
    'mass', 160, ...
    'inertia', diag([6000 3000 3000]), ...
    'vaneCount', 4, ...
    'vaneDofPerVane', 1, ...
    'vaneArea', 25, ...
    'vaneExtension', 5);

defaults.parameters.environment = struct( ...
    'Psrp', 4.563e-6, ...
    'eta', 1.8, ...
    'alphaCmd', atan(1 / sqrt(2)));

defaults.parameters.vanes = struct( ...
    'deflectionLimit', deg2rad(45), ...
    'rateLimit', deg2rad(5), ...
    'timeConstant', 10, ...
    'thetaLimit', deg2rad(40), ...
    'muTx', 5e-4);

defaults.parameters.rcd = struct( ...
    'quadrantArea', 40, ...
    'centroidOffset', 10, ...
    'reflectivityLimit', 0.30, ...
    'timeConstant', 20);

defaults.parameters.disturbance = struct( ...
    'enable', false, ...
    'cmCpOffset', 0.10);

defaults.controller = struct( ...
    'wn', [1.0e-3 1.0e-3 1.0e-3], ...
    'zeta', [0.80 0.80 0.80], ...
    'wi', [2.5e-4 2.5e-4 2.5e-4], ...
    'Tintmx', 2.5e-3, ...
    'gamma0', 0.10, ...
    'atrans', deg2rad(15), ...
    'esing', 1e-9, ...
    'useVaneYaw', true);

defaults.scenario = struct( ...
    'tEnd', 30000, ...
    'dt', 4.0, ...
    'summaryWindowFraction', 0.10);
end