clc;
clearvars;
close all;

% Initial conditions for each simulation case.
% Euler angles are specified in degrees; angular rates are in rad/s.
simulationCases = [
	struct('name', 'Zero attitude and rate', ...
		'eulerAnglesDeg', [0; 0; 0], ...
		'angularRateRadPerSec', [0; 0; 0]), ...
	struct('name', '55 degree attitude offset', ...
		'eulerAnglesDeg', [55; 55; 55], ...
		'angularRateRadPerSec', [0; 0; 0]), ...
	struct('name', 'Initial angular rate', ...
		'eulerAnglesDeg', [0; 0; 0], ...
		'angularRateRadPerSec', [0.02; 0.02; 0.02])
];

for caseIndex = 1:numel(simulationCases)
	simulationCase = simulationCases(caseIndex);
	fprintf('Running case %d: %s\n', caseIndex, simulationCase.name);

	initialEulerRad = deg2rad(simulationCase.eulerAnglesDeg);
	initialAngularRateRadPerSec = simulationCase.angularRateRadPerSec;

	solar_sail_attitude_control_Comparison( ...
		initialEulerRad, initialAngularRateRadPerSec);
end